spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_wave
    username: hello
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: bekbol.2019@gmail.com
    password: "zazz dhcs bjpo ogde"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: a@gmail.com
      text: someText
  output:
    ansi:
      enabled: always